import { createAction } from 'redux-actions';

const ON_ITEMS_LOAD_REQUEST = createAction('ON_ITEMS_LOAD_REQUEST');
const ON_ITEMS_LOAD_SUCCESS = createAction('ON_ITEMS_LOAD_SUCCESS');
const ON_ITEMS_LOAD_FAIL = createAction('ON_ITEMS_LOAD_FAIL');

const ON_CLOSE_ERROR_LOAD_NOTIFICATION = createAction('ON_CLOSE_ERROR_LOAD_NOTIFICATION');

export default {
  ON_ITEMS_LOAD_REQUEST,
  ON_ITEMS_LOAD_SUCCESS,
  ON_ITEMS_LOAD_FAIL,
  ON_CLOSE_ERROR_LOAD_NOTIFICATION,
};
