import { createAction } from 'redux-actions';

const ON_ITEM_DELETE = createAction('ON_PERSISTENCE_ITEM_DELETE');
const ON_ITEM_DELETE_SUCCESS = createAction('ON_PERSISTENCE_ITEM_DELETE_SUCCESS');
const ON_ITEM_DELETE_FAIL = createAction('ON_PERSISTENCE_ITEM_DELETE_FAIL');

const ON_ITEM_SAVE = createAction('ON_PERSISTENCE_ITEM_SAVE');
const ON_ITEM_SAVE_SUCCESS = createAction('ON_PERSISTENCE_ITEM_SAVE_SUCCESS');
const ON_ITEM_SAVE_FAIL = createAction('ON_PERSISTENCE_ITEM_SAVE_FAIL');

export default {
  ON_ITEM_DELETE,
  ON_ITEM_DELETE_SUCCESS,
  ON_ITEM_DELETE_FAIL,
  ON_ITEM_SAVE,
  ON_ITEM_SAVE_SUCCESS,
  ON_ITEM_SAVE_FAIL
};
