import { createAction } from 'redux-actions';

const ON_ITEMS_LOAD_REQUEST = createAction('ON_ITEMS_LOAD_REQUEST');
const ON_ITEMS_LOAD_SUCCESS = createAction('ON_ITEMS_LOAD_SUCCESS');
const ON_ITEMS_LOAD_FAIL = createAction('ON_ITEMS_LOAD_FAIL');

const ON_CLOSE_FAIL_NOTIFICATION = createAction('ON_CLOSE_FAIL_NOTIFICATION');

const ON_DELETION_SHOW_MODAL = createAction('ON_DELETION_SHOW_MODAL');
const ON_DELETION_CLOSE_MODAL = createAction('ON_DELETION_CLOSE_MODAL');
const ON_DELETION_PROCEED = createAction('ON_DELETION_PROCEED');

export default {
  ON_ITEMS_LOAD_REQUEST,
  ON_ITEMS_LOAD_SUCCESS,
  ON_ITEMS_LOAD_FAIL,
  ON_CLOSE_FAIL_NOTIFICATION,
  ON_DELETION_SHOW_MODAL,
  ON_DELETION_CLOSE_MODAL,
  ON_DELETION_PROCEED
};
