import { createAction } from 'redux-actions';

const ON_POKEMON_LOAD_REQUEST = createAction('ON_POKEMON_LOAD_REQUEST');
const ON_POKEMON_LOAD_STOP = createAction('ON_POKEMON_LOAD_STOP');
const ON_POKEMON_LOAD_SUCCESS_CONCAT = createAction('ON_POKEMON_LOAD_SUCCESS_CONCAT');
const ON_POKEMON_LOAD_SUCCESS_REPLACE = createAction('ON_POKEMON_LOAD_SUCCESS_REPLACE');
const ON_POKEMON_LOAD_FAIL = createAction('ON_POKEMON_LOAD_FAIL');
const ON_SET_SCROLL_AMOUNT_LIST = createAction('ON_SET_SCROLL_AMOUNT_LIST');
const ON_SET_SELECTED_ITEM = createAction('ON_SET_SELECTED_ITEM');

export default {
  ON_POKEMON_LOAD_REQUEST,
  ON_POKEMON_LOAD_STOP,
  ON_POKEMON_LOAD_SUCCESS_CONCAT,
  ON_POKEMON_LOAD_SUCCESS_REPLACE,
  ON_POKEMON_LOAD_FAIL,
  ON_SET_SCROLL_AMOUNT_LIST,
  ON_SET_SELECTED_ITEM
};
