import { createAction } from 'redux-actions';

const ON_POKEMON_LOAD_REQUEST = createAction('ON_POKEMON_LOAD_REQUEST');
const ON_POKEMON_LOAD_STOP = createAction('ON_POKEMON_LOAD_STOP');
const ON_POKEMON_LOAD_SUCCESS = createAction('ON_POKEMON_LOAD_SUCCESS');
const ON_POKEMON_LOAD_FAIL = createAction('ON_POKEMON_LOAD_FAIL');
const ON_SET_SCROLL_AMOUNT_LIST = createAction('ON_SET_SCROLL_AMOUNT_LIST');

export default {
  ON_POKEMON_LOAD_REQUEST,
  ON_POKEMON_LOAD_STOP,
  ON_POKEMON_LOAD_SUCCESS,
  ON_POKEMON_LOAD_FAIL,
  ON_SET_SCROLL_AMOUNT_LIST
};
