import { createAction } from 'redux-actions';

const ON_NOTIFICATION_SHOW = createAction('ON_NOTIFICATION_SHOW');
const ON_CLOSE_NOTIFICATION = createAction('ON_CLOSE_NOTIFICATION');
const ON_NOTIFICATION_CLOSE_FOREVER = createAction('ON_NOTIFICATION_CLOSE_FOREVER');

export default {
  ON_NOTIFICATION_SHOW,
  ON_CLOSE_NOTIFICATION,
  ON_NOTIFICATION_CLOSE_FOREVER
};
